
const OTP_PUBLIC_CONTEXTS = ['AUTH_LOGIN'];
const OTP_PRIVATE_CONTEXTS = ['UPDATE_PHONE','DEACTIVATE_STORE', 'DELETE_STORE', 'ACTIVATE_STORE'];

module.exports = {OTP_PUBLIC_CONTEXTS, OTP_PRIVATE_CONTEXTS};